// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnGpcwS1fO2fgoyVmNeDpELSwdrNv3_IU',
    appId: '1:501717798056:web:4c3d8ccd640c6184f8469d',
    messagingSenderId: '501717798056',
    projectId: 'teknato-6942a',
    authDomain: 'teknato-6942a.firebaseapp.com',
    storageBucket: 'teknato-6942a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrmSsxkBNzFZEN7g30OcYEUxYcVlXcPIc',
    appId: '1:501717798056:android:764e74cd194e0d94f8469d',
    messagingSenderId: '501717798056',
    projectId: 'teknato-6942a',
    storageBucket: 'teknato-6942a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5svVg2HkcMHY-NR-yu2na60ngfxaNRM0',
    appId: '1:501717798056:ios:63829da523586ff2f8469d',
    messagingSenderId: '501717798056',
    projectId: 'teknato-6942a',
    storageBucket: 'teknato-6942a.firebasestorage.app',
    iosBundleId: 'com.example.teknato',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5svVg2HkcMHY-NR-yu2na60ngfxaNRM0',
    appId: '1:501717798056:ios:63829da523586ff2f8469d',
    messagingSenderId: '501717798056',
    projectId: 'teknato-6942a',
    storageBucket: 'teknato-6942a.firebasestorage.app',
    iosBundleId: 'com.example.teknato',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnGpcwS1fO2fgoyVmNeDpELSwdrNv3_IU',
    appId: '1:501717798056:web:793d0f8c114502fdf8469d',
    messagingSenderId: '501717798056',
    projectId: 'teknato-6942a',
    authDomain: 'teknato-6942a.firebaseapp.com',
    storageBucket: 'teknato-6942a.firebasestorage.app',
  );
}
